# Generated by Django 2.0.2 on 2020-06-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete='models.CASCADE', to='df_goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete='models.CASCADE', to='df_user.UserInfo')),
            ],
        ),
    ]
