# Generated by Django 2.0.2 on 2020-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='ophone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='opostcode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='oreceive',
            field=models.CharField(default='', max_length=20),
        ),
    ]
